steps:
  - id: 'tf init'
    name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
      terraform init -backend-config=path/to/backend.tfvars

  - id: 'tf plan'
    name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
      terraform plan

  - id: 'tf apply'  # Manual approval recommended
    name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
      terraform apply

  - id: 'tf refresh'  # Optional
    name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
      terraform refresh